# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import test_pb2 as test__pb2


class AddNumStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.addnum = channel.unary_unary(
                '/AddNum/addnum',
                request_serializer=test__pb2.AddRequest.SerializeToString,
                response_deserializer=test__pb2.AddReply.FromString,
                )


class AddNumServicer(object):
    """Missing associated documentation comment in .proto file."""

    def addnum(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AddNumServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'addnum': grpc.unary_unary_rpc_method_handler(
                    servicer.addnum,
                    request_deserializer=test__pb2.AddRequest.FromString,
                    response_serializer=test__pb2.AddReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AddNum', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AddNum(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def addnum(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AddNum/addnum',
            test__pb2.AddRequest.SerializeToString,
            test__pb2.AddReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
